---
image: docker:19.03.1

services:
  - docker:19.03.1-dind

before_script:
  - apk update && apk add --no-cache docker
    python3 python3-dev py3-pip gcc git curl build-base
    autoconf automake py3-cryptography linux-headers
    musl-dev libffi-dev openssl-dev openssh
  - pip3 install --upgrade pip
  - pip3 install ansible molecule docker 'molecule[docker]'
  - docker info
  - python3 --version
  - ansible --version

molecule:
  stage: test
  script:
    - molecule test -s fast
