---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: wildfly-centos7-18.0.0-domain-controller
    image: geerlingguy/docker-centos7-ansible
    image_version: latest
    privileged: true
    groups:
      - domain_controller
      - wildfly_1800
  - name: wildfly-centos7-18.0.0-standalone
    image: geerlingguy/docker-centos7-ansible
    image_version: latest
    privileged: true
    groups:
      - standalone
      - wildfly_1800
  - name: wildfly-centos7-18.0.0-domain
    image: geerlingguy/docker-centos7-ansible
    image_version: latest
    privileged: true
    groups:
      - domain
      - wildfly_1800
  - name: wildfly-centos8-18.0.0-domain-controller
    image: geerlingguy/docker-centos8-ansible
    image_version: latest
    privileged: true
    groups:
      - domain_controller
      - wildfly_1800
      - python3
  - name: wildfly-centos8-18.0.0-standalone
    image: geerlingguy/docker-centos8-ansible
    image_version: latest
    privileged: true
    groups:
      - standalone
      - wildfly_1800
      - python3
  - name: wildfly-centos8-18.0.0-domain
    image: geerlingguy/docker-centos8-ansible
    image_version: latest
    privileged: true
    groups:
      - domain
      - wildfly_1800
      - python3
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      standalone:
        wildfly_mode: 'standalone'
      domain:
        wildfly_mode: 'domain'
      domain_controller:
        wildfly_mode: 'domain'
        wildfly_role: 'domain-master-slave'
      wildfly_1800:
        wildfly_version: 18.0.0.Final
      python3:
        ansible_python_interpreter: '/usr/bin/env python3'
      all:
        wildfly_installer_keep: true
        wildfly_installer_force_overwrite: false
        wildfly_installer_force_download: true
        wildfly_installer_local: true
        wildfly_manage_firewalld: false
        wildfly_service_status: 'started'
        wildfly_manage_service: false
        wildfly_management_users:
          - {name: 'david', password: 'ruomlig'}
          - {name: 'roger', password: 'sretaw'}
        wildfly_app_users:
          - {name: 'rich', password: 'thgirw'}
          - {name: 'nick', password: 'nosam'}
scenario:
  name: eighteen
verifier:
  name: testinfra
  lint:
    name: flake8
