---
- name: install init packages for CentOS 7
  hosts: all
  gather_facts: false
  tasks:
    - name: install initscripts package for CentOS 7
      raw: yum install -y initscripts
      become: true
      changed_when: false
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-wildfly
