---
# task file for wildfly

- name: create wildfly etc directory
  file:
    path: '{{ wildfly_conf_dir }}'
    state: directory
    owner: '{{ wildfly_user }}'
    group: '{{ wildfly_group }}'
    mode: '0750'

- name: copy wildfly configuration
  template:
    src: wildfly.conf.j2
    dest: '{{ wildfly_conf_dir }}/{{ wildfly_instance_name }}.conf'
    owner: root
    group: root
    mode: '0640'
  notify:
    - restart wildfly
    - change data mode

- name: copy wildfly domain-controller configuration
  template:
    src: wildfly-dc.conf.j2
    dest: '{{ wildfly_conf_dir }}/{{ wildfly_dc_instance_name }}.conf'
    owner: root
    group: root
    mode: '0640'
  notify:
    - restart wildfly services
    - change data mode
  when: wildfly_role == 'domain-master-slave'

- name: 'create domain user configuration in: {{ wildfly_base }}/domain/configuration'
  copy:
    src: '{{ item }}'
    dest: '{{ wildfly_base }}/domain/configuration/{{ item }}'
    owner: '{{ wildfly_user }}'
    group: '{{ wildfly_group }}'
    mode: '0600'
    force: false
  with_items:
    - application-roles.properties
    - application-users.properties
    - mgmt-groups.properties
    - mgmt-users.properties

- name: 'create domain server configuration in: {{ wildfly_base }}/domain/configuration'
  copy:
    src: '{{ wildfly_home }}/domain/configuration/{{ item }}'
    dest: '{{ wildfly_base }}/domain/configuration/{{ item }}'
    owner: '{{ wildfly_user }}'
    group: '{{ wildfly_group }}'
    mode: '{{ wildfly_file_mode }}'
    remote_src: true
    force: '{{ wildfly_config_file_force_overwrite }}'
  with_items:
    - default-server-logging.properties
    - domain.xml
    - host-master.xml
    - host-slave.xml
    - host.xml
    - logging.properties
  when: wildfly_mode == 'domain'

- name: 'create domain-controller user configuration in: {{ wildfly_base }}/domain-controller/configuration'
  copy:
    src: '{{ item }}'
    dest: '{{ wildfly_base }}/domain-controller/configuration/{{ item }}'
    owner: '{{ wildfly_user }}'
    group: '{{ wildfly_group }}'
    mode: '0600'
    force: false
  with_items:
    - application-roles.properties
    - application-users.properties
    - mgmt-groups.properties
    - mgmt-users.properties
  when: wildfly_role == 'domain-master-slave'

- name: 'create domain-controller server configuration in: {{ wildfly_base }}/domain-controller/configuration'
  copy:
    src: '{{ wildfly_home }}/domain/configuration/{{ item }}'
    dest: '{{ wildfly_base }}/domain-controller/configuration/{{ item }}'
    owner: '{{ wildfly_user }}'
    group: '{{ wildfly_group }}'
    mode: '{{ wildfly_file_mode }}'
    remote_src: true
    force: '{{ wildfly_config_file_force_overwrite }}'
  with_items:
    - default-server-logging.properties
    - domain.xml
    - host-master.xml
    - logging.properties
  when: wildfly_role == 'domain-master-slave'

- name: 'create standalone user configuration in: {{ wildfly_base }}/standalone/configuration'
  copy:
    src: '{{ item }}'
    dest: '{{ wildfly_base }}/standalone/configuration/{{ item }}'
    owner: '{{ wildfly_user }}'
    group: '{{ wildfly_group }}'
    mode: '0600'
    force: false
  with_items:
    - application-roles.properties
    - application-users.properties
    - mgmt-groups.properties
    - mgmt-users.properties

- name: 'create standalone server configuration configuration in: {{ wildfly_base }}/standalone/configuration'
  copy:
    src: '{{ wildfly_home }}/standalone/configuration/{{ item }}'
    dest: '{{ wildfly_base }}/standalone/configuration/{{ item }}'
    owner: '{{ wildfly_user }}'
    group: '{{ wildfly_group }}'
    mode: '{{ wildfly_dir_mode }}'
    remote_src: true
    force: '{{ wildfly_config_file_force_overwrite }}'
  with_items:
    - logging.properties
    - standalone-full-ha.xml
    - standalone-full.xml
    - standalone-ha.xml
    - standalone.xml
  when: wildfly_mode == 'standalone'

- name: create symlink to /etc/default/wildfly.conf
  file:
    state: link
    src: '{{ wildfly_conf_dir }}/{{ wildfly_instance_name }}.conf'
    dest: /etc/default/{{ wildfly_instance_name }}.conf

- include: configure-properties.yml

- name: create template to upstream init script
  template:
    src: wildfly_init.j2
    dest: '{{ wildfly_init_dir }}/{{ wildfly_instance_name }}'
    owner: root
    group: root
    mode: '0755'
    force: true
  #  when: ansible_service_mgr in ['init', 'upstart']
  notify:
    - restart wildfly services
    - change data mode

- name: copy wildfly domain-controller configuration
  template:
    src: wildfly-dc_init.j2
    dest: '{{ wildfly_init_dir }}/{{ wildfly_dc_instance_name }}'
    owner: root
    group: root
    mode: '0755'
  notify:
    - restart wildfly services
    - change data mode
  when: wildfly_role == 'domain-master-slave'

- block:
    - name: copy wildfly systemd unit file
      template: src=wildfly.service.j2 dest={{ wildfly_systemd_dir }}/{{ wildfly_instance_name }}.service owner=root
                group=root mode=0640
      notify:
        - restart wildfly services
        - change data mode
    - name: systemd reload
      systemd:
        daemon_reload: true
  when: ansible_service_mgr == 'systemd' and
        ((ansible_os_family == 'RedHat' and ansible_distribution_major_version|int > 6) or ansible_os_family != 'RedHat')

- block:
    - name: copy wildfly domain controller systemd unit file
      template: src=wildfly-dc.service.j2 dest={{ wildfly_systemd_dir }}/{{ wildfly_dc_instance_name }}.service owner=root
                group=root mode=0640
      notify:
        - restart wildfly services
        - change data mode
    - name: systemd reload
      systemd:
        daemon_reload: true
  when: wildfly_role == 'domain-master-slave' and ansible_service_mgr == 'systemd' and
        ((ansible_os_family == 'RedHat' and ansible_distribution_major_version|int  > 6) or ansible_os_family != 'RedHat')

- meta: flush_handlers

- block:
    - name: enable and start the standalone service
      service:
        name: '{{ wildfly_instance_name }}'
        state: started
        enabled: '{{ wildfly_service_enabled }}'
    - name: wait for wildfly to start
      wait_for:
        path: '{{ wildfly_console_log }}'
        search_regex: 'started in'
      ignore_errors: true
    - name: cat file
      command: '{{ wildfly_console_log }}'
      ignore_errors: true
  when: wildfly_manage_service and wildfly_mode == 'standalone'

- block:
    - name: enable and start the domain controller service
      service:
        name: '{{ wildfly_dc_instance_name }}'
        state: started
        enabled: '{{ wildfly_service_enabled }}'
    - name: wait for wildfly domain controller to start
      wait_for:
        path: '{{ wildfly_console_dc_log }}'
        search_regex: 'started in'
      ignore_errors: true
    - name: cat file
      command: 'cat {{ wildfly_console_dc_log }}'
      ignore_errors: true
  when: wildfly_manage_service and wildfly_mode == 'domain' and
        ( wildfly_role == 'domain-master-slave' or wildfly_role == 'domain-master')

- block:
    - name: enable and start the domain service
      service:
        name: '{{ wildfly_instance_name }}'
        state: started
        enabled: '{{ wildfly_service_enabled }}'
    - name: wait for wildfly to start
      wait_for:
        path: '{{ wildfly_console_log }}'
        search_regex: 'started in'
      ignore_errors: true
    - name: cat file
      command: 'cat {{ wildfly_console_log }}'
      ignore_errors: true
  when: wildfly_manage_service and wildfly_mode == 'domain' and
        (wildfly_role == 'domain-master-slave' or wildfly_role == 'domain-slave' or wildfly_role == 'domain')

- name: delete wildfly tar file
  file:
    path: '{{ wildfly_download_dir }}/{{ wildfly_download_file }}'
    state: absent
  when: not wildfly_installer_keep
