---

- name: copy wildfly properties file
  template:
    src: wildfly.properties.j2
    dest: '{{ wildfly_conf_dir }}/wildfly.properties'
    owner: '{{ wildfly_user }}'
    group: '{{ wildfly_group }}'
    mode: '0640'
  notify:
    - restart wildfly services
    - change data mode

- name: copy wildfly properties file
  template:
    src: wildfly-dc.properties.j2
    dest: '{{ wildfly_conf_dir }}/wildfly-dc.properties'
    owner: '{{ wildfly_user }}'
    group: '{{ wildfly_group }}'
    mode: '0640'
  notify:
    - restart wildfly services
    - change data mode
