---
# task file for wildfly

- name: check if Wildfly is installed.
  stat: path='{{ wildfly_dir }}/README.txt'
  register: wildfly_installed

- name: Install OpenJDK
  yum:
    name: java-1.8.0-openjdk-headless
    state: present
  when: wildfly_manage_java_pkg

- block:
    - name: create wildfly group
      group:
        name: '{{ wildfly_group }}'
        system: true
        state: present

    - name: create wildfly user
      user:
        name: '{{ wildfly_user }}'
        group: '{{ wildfly_group }}'
        createhome: false
        shell: "{{ wildfly_user_shell |default(omit) }}"
        state: present
        system: true
  when: wildfly_manage_user

- name: 'create application directory: {{ wildfly_dir }}'
  file:
    path: '{{ wildfly_dir }}'
    owner: '{{ wildfly_user }}'
    group: '{{ wildfly_group }}'
    mode: '{{ wildfly_dir_mode }}'
    recurse: true
    state: directory

- name: create wildfly link directory
  file:
    path: '{{ wildfly_install_dir }}/wildfly'
    owner: '{{ wildfly_user }}'
    group: '{{ wildfly_group }}'
    mode: '{{ wildfly_dir_mode }}'
    recurse: false
    state: directory

- name: create wildfly log directory
  file:
    path: '{{ wildfly_console_log_dir }}'
    owner: '{{ wildfly_user }}'
    group: '{{ wildfly_group }}'
    mode: '{{ wildfly_dir_mode }}'
    recurse: true
    state: directory

- name: create download directory
  file:
    path: '{{ wildfly_download_dir }}'
    owner: '{{ wildfly_user }}'
    group: '{{ wildfly_group }}'
    mode: '{{ wildfly_dir_mode }}'
    recurse: true
    state: directory

- name: is already downloaded locally
  stat:
    path: '{{ wildfly_download_file }}'
  delegate_to: localhost
  register: wildfly_is_local_download_file
  when: wildfly_installer_local

- name: is already downloaded
  stat:
    path: '{{ wildfly_download_dir }}/{{ wildfly_download_file }}'
  register: wildfly_is_download_file

- name: copy local wildfly tar file
  copy:
    src: '{{ wildfly_download_file }}'
    dest: '{{ wildfly_download_dir }}/{{ wildfly_download_file }}'
    mode: 0644
  when: (not wildfly_is_download_file.stat.exists or wildfly_installer_force_overwrite) and
        not wildfly_installer_force_download False and wildfly_installer_local

- block:
    - name: 'downloading Wildfly {{ wildfly_download_file }} to local machine'
      get_url:
        url: '{{ wildfly_download_url }}'
        validate_certs: '{{ wildfly_download_validate_certs }}'
        dest: './{{ wildfly_download_file }}'
        mode: 0644
      delegate_to: localhost
      run_once: true
      when: (not wildfly_is_local_download_file.stat.exists or wildfly_installer_force_overwrite) and
            wildfly_installer_force_download and wildfly_installer_local

    - name: copy downloaded wildfly tar file
      copy:
        src: '{{ wildfly_download_file }}'
        dest: '{{ wildfly_archive }}'
        mode: 0644
      when: (not wildfly_is_download_file.stat.exists or wildfly_installer_force_overwrite) and
            wildfly_installer_local
  when: wildfly_installer_local

- name: 'download wildfly tar file {{ wildfly_download_file }}'
  get_url:
    url: '{{ wildfly_download_url }}'
    dest: '{{ wildfly_download_dir }}/{{ wildfly_download_file }}'
    validate_certs: '{{ wildfly_download_validate_certs }}'
    mode: 644
  when: (not wildfly_is_download_file.stat.exists or wildfly_installer_force_overwrite) and
        wildfly_installer_force_download and not wildfly_installer_local

- name: 'unarchive downloaded {{ wildfly_download_file }} file'
  unarchive:
    src: '{{ wildfly_download_dir }}/{{ wildfly_download_file }}'
    dest: '{{ wildfly_install_dir }}/{{ wildfly_instance_name }}'
    owner: '{{ wildfly_user }}'
    group: '{{ wildfly_group }}'
    # mode: '{{ wildfly_dir_mode }}'
    copy: false
    creates: "{{ wildfly_dir }}/bin/{{ wildfly_mode }}.sh"
    exclude:
      - "configuration"
  when: not wildfly_installed.stat.exists or force_wildfly_install

- name: 'create domain configuration directory in: {{ wildfly_dir }}'
  file:
    path: '{{ wildfly_dir }}/domain/{{ item }}'
    owner: '{{ wildfly_user }}'
    group: '{{ wildfly_group }}'
    mode: '{{ wildfly_dir_mode }}'
    recurse: true
    state: directory
  with_items:
    - configuration
    - data/content
    - tmp/auth
  when: wildfly_mode == 'domain'

- name: 'create domain-controller configuration directory in: {{ wildfly_dir }}'
  file:
    path: '{{ wildfly_dir }}/domain-controller/{{ item }}'
    owner: '{{ wildfly_user }}'
    group: '{{ wildfly_group }}'
    mode: '{{ wildfly_dir_mode }}'
    recurse: true
    state: directory
  with_items:
    - configuration
    - data/content
    - tmp/auth
  when: wildfly_role == 'domain-master-slave'

- name: 'create standalone configuration directory in: {{ wildfly_dir }}'
  file:
    path: '{{ wildfly_dir }}/standalone/{{ item }}'
    owner: '{{ wildfly_user }}'
    group: '{{ wildfly_group }}'
    mode: '{{ wildfly_dir_mode }}'
    recurse: true
    state: directory
  with_items:
    - configuration
    - deployments
    - lib/ext
    - tmp/auth
  when: wildfly_mode == 'standalone'

- name: 'create configuration directory for domain and standalone'
  file:
    path: '{{ wildfly_dir }}/{{ item }}'
    owner: '{{ wildfly_user }}'
    group: '{{ wildfly_group }}'
    mode: '{{ wildfly_dir_mode }}'
    recurse: true
    state: directory
  with_items:
    - domain/configuration
    - standalone/configuration

- name: create symlink to installed version
  file:
    state: link
    src: '{{ wildfly_dir }}'
    dest: '{{ wildfly_link_dir }}'
    force: true
  when: wildfly_create_symlink
