---
# task file for wildfly

- include_tasks: install.yml
- include_tasks: configure.yml
- include_tasks: ulimits.yml
- include_tasks: users.yml

- include_tasks: ssl.yml
  when: wildfly_enable_ssl

- name: manage firewalld
  include_tasks: manage_firewalld.yml
  when: wildfly_manage_firewalld
