---
# task file for wildfly

- name: install Wildfly prerequisite
  include_tasks: install-prerequisite.yml

- name: download Wildfly installer
  include_tasks: download.yml

- name: install Wildfly
  include_tasks: install.yml

- name: configure Wildfly
  include_tasks: configure.yml

- include_tasks: ulimits.yml
- include_tasks: users.yml

- include_tasks: ssl.yml
  when: wildfly_enable_ssl

- include_tasks: vault.yml
  when: wildfly_vault_enable

- name: manage firewalld
  include_tasks: manage_firewalld.yml
  when: wildfly_manage_firewalld

- include_tasks: service.yml
