---
# task file for wildfly

- include_tasks: install-prerequisite.yml
- include_tasks: download.yml
- include_tasks: install.yml
- include_tasks: configure.yml
- include_tasks: users.yml

- include_tasks: ssl.yml
  when: wildfly_enable_ssl
