---
# task file for wildfly manage firewalld

- name: install firewalld package
  package:
    name: firewalld
    state: present

- name: ensure firewalld is running and enabled on boot
  service:
    name: firewalld
    state: started
    enabled: true

- block:
    - name: open wildfly management http tcp port
      firewalld:
        port: '{{ wildfly_management_http_port }}/tcp'
        permanent: true
        immediate: true
        state: enabled

    - name: open wildfly management https tcp port
      firewalld:
        port: '{{ wildfly_management_https_port }}/tcp'
        permanent: true
        immediate: true
        state: enabled

    - name: open wildfly http tcp port
      firewalld:
        port: '{{ wildfly_http_port }}/tcp'
        permanent: true
        immediate: true
        state: enabled

    - name: open wildfly https tcp port
      firewalld:
        port: '{{ wildfly_https_port }}/tcp'
        permanent: true
        immediate: true
        state: enabled
  when: ((ansible_os_family == 'RedHat' and ansible_distribution_major_version|int  > 6) or ansible_os_family != 'RedHat') and wildfly_manage_firewalld
