- block:
    - name: enable and start the standalone service
      service:
        name: '{{ wildfly_instance_name }}'
        state: '{{ wildfly_service_status }}'
        enabled: '{{ wildfly_service_enabled }}'
    - name: wait for wildfly to start
      wait_for:
        path: '{{ wildfly_console_log }}'
        search_regex: 'started in'
        timeout: 600
        delay: 10
        sleep: 3
      ignore_errors: true
    - name: cat file
      command: '{{ wildfly_console_log }}'
      ignore_errors: true
      changed_when: false
  when: wildfly_manage_service and wildfly_mode == 'standalone'

- block:
    - name: enable and start the domain controller service
      service:
        name: '{{ wildfly_dc_instance_name }}'
        state: '{{ wildfly_service_status }}'
        enabled: '{{ wildfly_service_enabled }}'
    - name: wait for wildfly domain controller to start
      wait_for:
        path: '{{ wildfly_console_dc_log }}'
        search_regex: 'started in'
        timeout: 600
        delay: 10
        sleep: 3
      ignore_errors: true
      changed_when: false
    - name: cat file
      command: 'cat {{ wildfly_console_dc_log }}'
      ignore_errors: true
      changed_when: false
  when:
    - wildfly_manage_service
    - wildfly_mode == 'domain'
    - wildfly_role in [ 'domain-master-slave', 'domain-master' ]

- block:
    - name: enable and start the domain service
      service:
        name: '{{ wildfly_instance_name }}'
        state: '{{ wildfly_service_status }}'
        enabled: '{{ wildfly_service_enabled }}'
    - name: wait for wildfly to start
      wait_for:
        path: '{{ wildfly_console_log }}'
        search_regex: 'started in'
        timeout: 600
        delay: 10
        sleep: 3
      ignore_errors: true
      changed_when: false
    - name: cat file
      command: 'cat {{ wildfly_console_log }}'
      ignore_errors: true
      changed_when: false
  when:
    - wildfly_manage_service
    - wildfly_mode == 'domain'
    - wildfly_role in [ 'domain-master-slave', 'domain-slave' ]

- meta: flush_handlers
