---
# vault tasks file for wildfly

- block:
  - name: 'create Wildfly secure store directory'
    file:
      path: '{{ wildfly_vault_path }}'
      owner: '{{ wildfly_user }}'
      group: '{{ wildfly_group }}'
      mode: '0750'
      state: directory

  - name: create Wildfly Vault store
    become: true
    become_user: '{{ wildfly_user }}'
    shell: >
        {{ wildfly_java_home }}/bin/keytool -genseckey -alias {{ wildfly_vault_alias }} -storetype jceks \
        -keyalg {{ wildfly_vault_keyalg }} -keysize {{ wildfly_vault_keysize }} \
        -storepass {{ wildfly_vault_keystore_password }} -keypass {{ wildfly_vault_keystore_password }} \
        -keystore {{ wildfly_vault_file }} -dname '{{ wildfly_vault_dname }}'
    args:
        creates: "{{ wildfly_vault_file }}"
    no_log: false

  - name: create Wildfly Vault secrets
    become: true
    become_user: '{{ wildfly_user }}'
    shell: >
        {{ wildfly_base }}/bin/vault.sh -k {{ wildfly_vault_file }} -p {{ wildfly_vault_keystore_password }} \
        -e {{ wildfly_vault_path }} -i {{ wildfly_vault_iteration }} -s {{ wildfly_vault_salt }} \
        -v {{ wildfly_vault_alias }} -b {{ item.block }} -a {{ item.attribute }} -x {{ item.value }}
    with_items: '{{ wildfly_vault }}'
    no_log: false

  - name: 'setting domain member to use vault'
    xml:
      path: '{{ wildfly_base }}/domain/configuration/host-slave.xml'
      xpath: '/h:host/h:vault'
      input_type: 'xml'
      namespaces:
        h: 'urn:jboss:domain:{{ wildfly_file_version }}'
      add_children:
        - '<vault-option name="KEYSTORE_URL" value="{{ wildfly_vault_file }}" />'
        - '<vault-option name="KEYSTORE_PASSWORD" value="{{ wildfly_vault_keystore_password }}" />'
        - '<vault-option name="KEYSTORE_ALIAS" value="{{ wildfly_vault_alias }}" />'
        - '<vault-option name="SALT" value="{{ wildfly_vault_salt }}" />'
        - '<vault-option name="ITERATION_COUNT" value="{{ wildfly_vault_iteration }}" />'
        - '<vault-option name="ENC_FILE_DIR" value="{{ wildfly_vault_path }}" />'
      pretty_print: true
    when:
      - wildfly_mode == 'domain'
      - wildfly_role in [ 'domain-master-slave', 'domain-slave' ]
    notify: restart wildfly services
    no_log: false
  when:
    - wildfly_vault_enable
