---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: wildfly-centos8-default
    image: geerlingguy/docker-centos8-ansible
    image_version: latest
    privileged: true
    groups:
      - wildfly_1800
      - python3
      - standalone
  - name: wildfly-centos8-default-domain
    image: geerlingguy/docker-centos8-ansible
    image_version: latest
    privileged: true
    groups:
      - wildfly_1800
      - python3
      - domain
  - name: wildfly-centos8-default-domain_controller
    image: geerlingguy/docker-centos8-ansible
    image_version: latest
    privileged: true
    groups:
      - wildfly_1800
      - python3
      - domain_controller
  - name: wildfly-centos8-default-domain_controller_backup
    image: geerlingguy/docker-centos8-ansible
    image_version: latest
    privileged: true
    groups:
      - wildfly_1800
      - python3
      - domain_controller
      - domain_backup
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      standalone:
        wildfly_mode: 'standalone'
      domain:
        wildfly_mode: 'domain'
      domain_controller:
        wildfly_mode: 'domain'
        wildfly_role: 'domain-master-slave'
      wildfly_1800:
        wildfly_version: 18.0.0.Final
        wildfly_file_version: '10.0'
      domain_backup:
        wildfly_dc_backup_mode: true
        wildfly_dc_cached_mode: true
      all:
        wildfly_installer_keep: true
        wildfly_installer_force_overwrite: false
        wildfly_installer_force_download: true
        wildfly_installer_local: true
        wildfly_manage_firewalld: false
        wildfly_service_status: 'started'
        wildfly_manage_service: false
        wildfly_management_users:
          - {name: 'david', password: 'ruomlig'}
          - {name: 'roger', password: 'sretaw'}
        wildfly_app_users:
          - {name: 'rich', password: 'thgirw'}
          - {name: 'nick', password: 'nosam'}
scenario:
  name: fast
verifier:
  name: testinfra
  lint:
    name: flake8
